version: "3.9"

services:
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      - ROBOT_BROWSER_HEADLESS=True
    volumes:
      - ./tests/output:/app/output
    command: []   # entrypoint.sh handles running Robot
    networks:
      - prediction-network
    depends_on:
      - frontend
      - backend

networks:
  prediction-network:
