name: Test and Deploy

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:

  test:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker-compose tests
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from test test

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down


  deploy_backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Backend Deploy
        run: |
          echo "Deploying backend..."
          curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}


  deploy_frontend:
    name: Deploy Frontend to Render
    runs-on: ubuntu-latest
    needs: deploy_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Frontend Deploy
        run: |
          echo "Deploying frontend..."
          curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
