name: Test and Deploy

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    env:
      ENV: ${{ vars.ENV }}
      FRONTEND_URL: ${{ vars.FRONTEND_URL }}
      BACKEND_URL: ${{ vars.BACKEND_URL }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}
      FRONTEND_PORT: ${{ vars.FRONTEND_PORT }}
      PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
      PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with full compose stack
        run: |
          # In CI we MUST override the external URLs with internal Docker hostnames
          export VITE_API_URL="http://backend:8000"
          export FRONTEND_URL="http://frontend:5173"

          docker compose -f docker-compose.yml -f docker-compose.test.yml up \
            --abort-on-container-exit \
            --exit-code-from test

      - name: Save Robot test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-output
          path: ./tests/output

      - name: Cleanup containers
        if: always()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml down -v

  deploy_backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Backend Deploy
        env:
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
        run: |
          echo "Deploying backend..."
          curl -X POST "$RENDER_BACKEND_HOOK"


  deploy_frontend:
    name: Deploy Frontend to Render
    runs-on: ubuntu-latest
    needs: deploy_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Frontend Deploy
        env:
          RENDER_FRONTEND_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          echo "Deploying frontend..."
          curl -X POST "$RENDER_FRONTEND_HOOK"
